apps/servicio_tecnico/urls.py
from apps.servicio_tecnico.views import home, presupuesto, trabajos
from django.urls.conf import path
from django.urls.conf import re_path
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

favicon_view = RedirectView.as_view(url='/static/img/favicon.ico', permanent=True)


app_name = 'apps.servicio_tecnico'

urlpatterns = [
    path('', home, name='home'),
    path('api/trabajos',trabajos,name="trabajos"),
    path('servicio_tecnico/presupuesto',presupuesto,name="presupuesto"),
    #FavIcon    
    re_path(r'^favicon\.ico$', favicon_view),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.servicio_tecnico.urls',namespace='servicio_tecnico')), 
]

apps/servicio_tecnico/models.py
from django.db import models

# Create your models here.
class BaseModel(models.Model):
    creado = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now_add=True)

    class Meta:
        abstract = True

class Categoria(BaseModel):
    nombre_categoria = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre_categoria

class Jobs(BaseModel):
    categoria = models.ForeignKey(Categoria, related_name='categoria',on_delete=models.CASCADE)
    nombre = models.CharField(max_length=150,null=False)
    valor = models.DecimalField(max_digits=6,decimal_places=2,default=0)

    def __str__(self):
        return self.nombre

apps/servicio_tecnico/views.py
from apps.servicio_tecnico.models import Jobs
from django.shortcuts import render
from django.http.response import HttpResponse, JsonResponse

# Create your views here.

def home(request):
    return render(request,'index.html')

def trabajos(request):
    try:
        trabajo = Jobs.objects.all()
        trabajo = list(trabajo)
        data = []
        for t in trabajo:
            data.append({
                'categoria': t.categoria.nombre_categoria,
                'trabajo' : t.nombre,
                'precio' : t.valor,
            })

        payload = {'status': True, 'data': data}
        return JsonResponse(payload)

    except Exception as e:
        print(e)
    return HttpResponse("Algo malio sal")


def presupuesto(request):

    context = {
        'categoria': request.GET.get('categoria'),
        'trabajo' : request.GET.get('user_id'),
        'precio' : request.GET.get('puntaje'),
    }
    return render(request,'servicio_tecnico/presupuesto.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-AR">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" href="{% static 'favicon.ico'%}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icono/apple-touch-icon.png' %}">
    <link rel="manifest" href="{% static 'icono/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'icono/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="{% static 'icono/browserconfig.xml' %}">
    <meta name="theme-color" content="#EEEEEE">

    <title>Rodrigo Costa</title>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Iconos Materialize -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Iconos DevIcons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.14.0/devicon.min.css">
    <link href="{% static '/css/base.css'%}" type="text/css" rel="stylesheet" media="screen,projection" />
</head>
<!-- VUE JS -->
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

<body class="center" style="background-color:var(--black);">
    <!-- NavBar -->
    <div class="navbar-fixed">
        <nav class="blue darken-3">
            <div class="nav-wrapper container">
                <a href="{% url 'servicio_tecnico:home' %}" class="brand-logo text-decoration-none">RAC</a >

                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li>
                        <a href="https://drive.google.com/file/d/1C9vgTO1jEvKw1GyJBfFogkZ1CljfdBRY/view" target="_blank">
                            RESUME
                        </a>
                </li>
                <li>
                    <a href="http://www.linkedin.com/in/rodrigo-andrés-costa-6824b95a" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="#FFD369" class="bi bi-linkedin" viewBox="0 0 16 16">
                                <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
                            </svg>
                    </a>
                </li>
                <li>
                    <a href="https://github.com/RodriDesmond/" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="#FFD369" class="bi bi-github" viewBox="0 0 16 16">
                                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                            </svg>
                    </a>
                </li>
                </ul>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            </div>
        </nav>
    </div>
    <ul class="sidenav" id="mobile-demo">
        <br />
        <div style="text-align:center;"> <br />
            <a class="h3" style="text-decoration: none; color: var(--dark);" href="{% url 'servicio_tecnico:home' %}" class="brand-logo">RAC</a >
          </div>
          <br/><br/>
            <li><a href="#trabajos">Projects</a></li>
            <li><a href="#experiencia">Experience</a></li>
            <li><a href="#educacion">Education</a></li>
            <li><a href="#habilidades">Skills</a></li>
            <li>
                </br>
            </li>
            <li><a href="#contacto">Contact me</a></li>
            <li><a href="{% url 'servicio_tecnico:presupuesto' %}">Servicio IT</a></li>
    </ul>
    <!-- parallax  -->
    <div class="parallax-container" id="inicio">
        <div class="section no-pad-bot">
            <div class="container">
                <br><br>
                <h1 class="header center teal-text text-lighten-2"></h1>
                <div class="row center">
                    <h1 class="header center teal-text text-lighten-2"></h1>
                    <h1 class="header center teal-text text-lighten-2"></h1>
                </div>
                <div class="row center">
                    <h1 class="header center teal-text text-lighten-2"></h1>
                    <h1 class="header center teal-text text-lighten-2"></h1>
                </div>
                <div class="row center">
                    <h1 class="titulo" id="hello" style="letter-spacing: 2px;">RODRIGO COSTA</h1>
                </div>
                <div class="row hide-on-med-and-down">
                    <div class="col">
                        <a class="waves-effect waves-light btn" href="#trabajos">Projects</a>
                        <a class="waves-effect waves-light btn" href="#contacto">Contact</a>
                        <a class="waves-effect waves-light btn" href="{% url 'servicio_tecnico:presupuesto' %}">Servicio IT</a>
                    </div>
                </div>
                <br><br>
            </div>
        </div>
        <div class="parallax"><img src="{% static '/img/background.jpg' %}" alt="Unsplashed background img 1"></div>
    </div>
    {% block content %} {% endblock %}
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!--  Scripts-->
    <script src="{% static '/apps/init.js' %}" type="text/javascript"></script>
</body>

</html>

templates/servicio_tecnico/presupuesto.html
{% extends 'base.html' %}{% load static %} {% block content %}

<link href="{% static '/css/presupuesto.css'%}" type="text/css" rel="stylesheet" media="screen,projection" />
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!-- Modal Structure -->
<div id="modal1" class="modal bottom-sheet">
    <div class="modal-content">
        <h3 class="header" style="color: red;">Esta Secccion Esta en Construccion</h3>
        <ul class="collection">
            <li class="collection-item avatar">
                <img src="{% static 'img/profile.jpg'%}" alt class="circle">
                <span class='title'>Servicio Tecnico</span>
            </li>
            <li class="collection-item avatar">
                <i class="material-icons circle green">textsms</i>
                <span class='title'>WhatsApp: 3644 725019</span>
            </li>
        </ul>
        <p style="color: var(--dark);">La Escondida, Chaco - </p>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-close waves-effect waves-green btn-flat center">Cerrar</a>
    </div>
</div>
<div id="app">
    <div class="container section">
        <div class="col s12">
            <h2 style="color:var(--bg)">Servicio Base</h2>
            <table style="color: #EEEEEE; text-align: left;">
                <thead>
                    <tr>
                        <th>Trabajo</th>
                        <th>Valor</th>
                        <th>Cantidad</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(t,i) in trabajos" v-if="t.categoria === 'Servicio Tecnico'" :key="i">
                        <td style="max-width: 10rem;">[[t.trabajo]]</td>
                        <td>$[[t.precio]]</td>
                        <td>
                            <input v-model="t.cant" type="number" :name="'cant-'+i" :id="'cant-'+i"
                                style="max-width: 3rem; color: var(--txt);" min="0">
                        </td>
                        <td>
                            <input v-on:click="counter = counter + parseFloat(t.cant) * parseFloat(t.precio)"
                                class="waves-effect waves-light btn" value="Agregar" type="button">
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col s12">
            <h2 style="color:var(--bg)">Hardware</h2>
            <table style="color: #EEEEEE; text-align: left;">
                <thead>
                    <tr>
                        <th>Trabajo</th>
                        <th>Valor</th>
                        <th>Cantidad</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(t,i) in trabajos" v-if="t.categoria === 'Hardware'" :key="i">
                        <td style="max-width: 10rem;">[[t.trabajo]]</td>
                        <td>$ [[t.precio]]</td>
                        <td>
                            <input v-model="t.cant" type="number" :name="'cant-'+i" :id="'cant-'+i"
                                style="max-width: 3rem; color: var(--txt);" min="0">
                        </td>
                        <td>
                            <input @click="counter = counter + parseFloat(t.cant) * parseFloat(t.precio)"
                                class="waves-effect waves-light btn" value="Agregar" type="button">
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="container section" style="text-align: left;">
        <div class="col s12">
            <ul v-for="index in trabajos">
                <li v-show="index.cant > 0">
                    <h4 style="color: white">[[index.trabajo]]</h4>
                    <p> Cantidad: [[index.cant]] = $ [[sub = parseFloat(index.cant)
                        * parseFloat(index.precio)]]</p>
                </li>
            </ul>
        </div>
    </div>
    <h2 style="color: white">Presupuesto: $[[counter]]</h2>
    <input v-on:click="counter = 0" class="waves-effect waves-light btn red" value="Resetear" type="button">
    <input v-on:click="counter = 0" class="waves-effect waves-light btn" value="Generar" type="button">
</div>

<div class="container section">
    <h1 style="color: red">Seccion en progreso.</h1>
    <h2 style="color: white">La Escondida, Chaco - Argentina</h2>
</div>
<script src="{% static '/apps/presupuesto.js' %} "></script>
{% endblock %}